config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  Rails.application.routes.default_url_options[:host] = 'XXX'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, path: :users, path_names: { sign_in: :login, sign_out: :logout, sign_up: :signup }

  root to: 'accounts#show'

  resources :accounts, only: :show

  resources :credits

  resources :transfers
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :credits, dependent: :destroy

  validates :number, uniqueness: { case_sensitive: false }
  validates :balance, presence: true
  validates :balance, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def increase_balance(amount)
    self.balance += amount
    save
  end

  def decrease_balance(amount)
    self.balance -= amount
    save
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user
  belongs_to :account

  validates :debts, presence: true
  validates :debts, numericality: { only_integer: true, greater_than: 0 }

  after_create :send_notification

  private

  def send_notification
    NewCreditsNotificationJob.perform_later(user, self)
  end
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  validates :amount, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable,
         :trackable

  after_create :set_account

  has_one :account, dependent: :destroy
  has_many :credits, dependent: :destroy
  has_many :sender_transfers, class_name: 'Transfer', foreign_key: :sender_id, dependent: :destroy, inverse_of: :sender
  has_many :receiver_transfers, class_name: 'Transfer', foreign_key: :receiver_id, dependent: :destroy,
                                inverse_of: :receiver

  validates :email, uniqueness: { case_sensitive: false }
  validates :first_name, presence: true
  validates :last_name, presence: true

  def transfers
    Transfer.includes(%i[receiver sender]).where('sender_id = :id or receiver_id = :id', { id: id })
  end

  private

  def set_account
    Account.create(number: random.to_s, user_id: id)
  end

  def random
    (0...3).map { rand(100) }.join
  end
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  before_action :authenticate_user!

  def show
    @credits = current_user.credits
    @transfers = current_user.transfers
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, unless: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
  end
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  before_action :authenticate_user!

  def new
    @credit = account.credits.new
  end

  def create
    @credit = account.credits.new(credit_params)
    @credit.user = current_user

    if @credit.save
      account.increase_balance(@credit.debts)
      render :'credits/show'
    else
      render :new
    end
  end

  private

  def account
    @account ||= current_user.account
  end

  def credit_params
    params.require(:credit).permit(:debts, :active, :account_id, :user_id)
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :authenticate_user!

  def new
    @transfer = current_user.sender_transfers.new
  end

  def create
    result = transfer_create_service

    if result.errors.empty? && result.transfer.present?
      render :'transfers/show'
    else
      flash[:notice] = result.errors
      redirect_to new_transfer_path
    end
  end

  private

  def transfer_create_service
    Transfer::CreateService.new(
      amount: params[:transfer][:amount],
      account_number: params[:transfer][:cipher],
      sender_account: current_user.account
    ).call
  end

  def transfer_params
    params.require(:transfer).permit(:amount, :cipher)
  end
end

app/controllers/users/devise_controller.rb
# frozen_string_literal: true

module Users
  class DeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => e
        raise e if get?

        if has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end

    self.responder = Responder
    respond_to :html, :turbo_stream
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/accounts/show.html.erb
<div>
  <h2><%= link_to "Open new credits", new_credit_path(@account) %></h2>
</div>

<div>
  <h2><%= link_to "Send money to other client", new_transfer_path(@account) %></h2>
</div>

<div class="account">
<h2>Account number:  <%= current_user.account.number %></h2>
<h2>Your balance:  <%= current_user.account.balance %></h2>
</div>

<div>
  <table class="credits">
    <caption>Client credits</caption>
    <tr>
      <td>CREDIT ID</td>
      <td>CREDIT AMOUNT</td>
      <td>ACTIVE CREDIT</td>
    </tr>
    <%= render @credits %>
  </table>
</div>

<div>
  <table class="transfers">
    <caption>Client transfers</caption>
    <tr>
      <td>TRANSFER ID</td>
      <td>TRANSFER AMOUNT</td>
      <td>SENDER</td>
      <td>RECEIVER</td>
      <td>DATA</td>
    </tr>
    <%= render @transfers %>
  </table>
</div>

app/views/credits/_credit.html.erb
<tr>
  <th><%= credit.id %></th>
  <th><%= credit.debts %></th>
  <th><%= credit.active %></th>
</tr>

app/views/credits/_form.html.erb
<%= form_with model: @credit, data: {turbo: false}, local: true do |f| %>
  <%= render 'shared/errors', resource: @credit  %>

  <h2><p>
    <%= f.label :debts %><br>
    <%= f.number_field :debts %>
  </p></h2><br>

  <h3><p><%= f.submit %></p></h3>
<% end %>

app/views/credits/new.html.erb
<h1>Create new credit</h1>

<%= render 'form' %>

app/views/credits/show.html.erb
<h2>Credit successfully created!</h2>

<h2><%= link_to 'Back to home', root_path %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'shared/header' %>

  <%= render 'shared/flash' %>

    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.errors.present? %>
  <div>
    <h2>
      <%= resource.errors.count %>:
    </h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, message, class: "flash #{key}" %>
<% end %>

app/views/shared/_header.html.erb
<header class="nav">
  <%if user_signed_in? %>
    <h3><b><%= current_user.first_name%></b>  <b><%=  current_user.last_name  %></b></h3>
    <h4><%= link_to "Log out", destroy_user_session_path,
                    data: {"turbo-method": :delete},
                    class: "btn btn-danger ml-3"%></h4>
  <% end %>
</header>

app/views/transfers/_form.html.erb
<%= form_with model: @transfer, data: {turbo: false}, local: true do |f| %>

  <h2><p>
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </p></h2><br>

  <h2><p>
    <%= f.label :cipher %><br>
    <%= f.text_field :cipher %>
  </p></h2><br>

  <h3><p><%= f.submit %></p></h3>
<% end %>

app/views/transfers/_transfer.html.erb
<tr>
  <th><%= transfer.id %></th>
  <th><%= transfer.amount %></th>
  <th><%= transfer.sender.email %></th>
  <th><%= transfer.receiver.email %></th>
  <th><%= transfer.created_at %></th>
</tr>

app/views/transfers/new.html.erb
<h1>Money transfer</h1>

<%= render 'form' %>

app/views/transfers/show.html.erb
<h2>Transfer was successfully completed!</h2>

<h2><%= link_to 'Back to home', root_path %></h2>